import { OnDestroy } from "@angular/core";
import { ActivatedRoute } from "@angular/router";
import { ApplicationService } from "../../../../services/application.service";
import { IntegrationsAWSService } from "../../../../services/integrations.aws.service";
import { IApplication, IAWS } from "../../../../models/interfaces";
import { ModalService } from "../../../../services/modal.service";
import { MessageService } from "../../../../services/message.service";
export declare class TeleportDevPortalAppIntegrationAwsComponent implements OnDestroy {
    private route;
    private apps;
    private aws;
    private modal;
    private message;
    isBusy: boolean;
    isEditing: boolean;
    accessKey: string;
    securityKey: string;
    bucket: string;
    region: string;
    private _application;
    private _aws;
    constructor(route: ActivatedRoute, apps: ApplicationService, aws: IntegrationsAWSService, modal: ModalService, message: MessageService);
    ngOnDestroy(): void;
    readonly App: IApplication;
    readonly AWS: IAWS;
    edit(): void;
    clear(): void;
    save(): void;
    cancel(): void;
}
